
OCAMLC=ocamlc
OCAMLDEP=ocamldep
OCAMLLEX=ocamllex
OCAMLYACC=ocamlyacc

OFLAGS=-w A # warn about everything
# OFLAGS=-w -A # silence everything


LIBS = str.cma
MD_OBJS = blocks.cmo parser.cmo scanner.cmo markdown.cmo
AST_OBJS = blocks.cmo parser.cmo scanner.cmo ast_printer.cmo

default: clean markdown ast test

test:
	./ast < testing/test_headers.md

markdown: $(MD_OBJS)
	$(OCAMLC) $(LIBS) -o markdown $(MD_OBJS)

ast: $(AST_OBJS)
	$(OCAMLC) $(LIBS) -o ast $(AST_OBJS)

scanner.ml: scanner.mll
	$(OCAMLLEX) scanner.mll

parser.ml parser.mli: parser.mly
	$(OCAMLYACC) parser.mly

tar: $(TARFILES)
	cd .. && tar czf markdown.tar.gz `git ls-files markdown`

.PHONY: clean markdown test all
clean:
	rm -f markdown parser.ml parser.mli scanner.ml \
		*.cmo *.cmi *.out *.diff

%.cmo: %.ml
	$(OCAMLC) $(OFLAGS) -c $<

%.cmi: %.mli
	$(OCAMLC) $(OFLAGS) -c $<

# Generated by ocamldep *.mli *.ml
parser.cmi : blocks.cmo
ast_printer.cmo : scanner.cmo parser.cmi blocks.cmo
ast_printer.cmx : scanner.cmx parser.cmx blocks.cmx
blocks.cmo :
blocks.cmx :
markdown.cmo : scanner.cmo parser.cmi blocks.cmo
markdown.cmx : scanner.cmx parser.cmx blocks.cmx
parser.cmo : blocks.cmo parser.cmi
parser.cmx : blocks.cmx parser.cmi
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
